# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlexBoxUIKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlexUIKitExample
  pod "FlexBoxUIKit", :path => "../"
  pod "FlexBoxUIKit/SDWebImage", :path => "../"
  pod "Then"
#  pod 'Kingfisher', '~> 6.3.1'
#  pod "SDWebImage"
end
